<?php
// SET DEFAULT TIME-ZONE
date_default_timezone_set('	Europe/London');

// JWT VARIABLES
$token_issued = time();
$token_expiration = time() + (60 * 720);

// THESE ARE TEMPORARY KEYS, THEY WILL BE REPLACED LATER ON
$privateKey = "
-----BEGIN PRIVATE KEY-----
MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAKbPONO0aF1QY+CB
vvpZdXUd484qkeDyAQMQf6ZKw5Rz2r89PCfvDe7kEvd9oLh0ZT4AFHbijnCLTm1h
GQ7JiFZMojE3BzXYam6OQ6SCK4kcVZmyfZJQ+ImqBfBY5TIgOlNMH4GbJIj1BJzR
Rg5S5jngOQMQ++JeueIH8GZJCERrAgMBAAECgYBDYYd59PEHaJa/tIlZhVNt+KHx
wL5mmDsSatK1cJPqXpYpE+o901HUguqqcGPAvru6vLuHfmK9UXhftI4zq/LXClUG
fHiCrkUcnsagUfH0xsmoFcKIOGVe8C//yJh4jmnb7zSphO0zml2xgT5UCnwHrpUV
T6qaH0Ns1mzOqzcssQJBANY5PN9w7a7u0ClrvNyThW8t1HCSAvNW/SNTWsjnhk/Q
Gmc9SNq+o3EdDtqKV9mMQIZmySIbkGtHHGL2dVTIlCMCQQDHVulck7BU9lXDDGJg
OgDJl2A6hDbnNp85Fb44U+sgUOb3nmqsWrZvYaR3j8mwykrJoXNgb0IBjUluiU+n
iU8ZAkEApB0fbFIYVJ6xrDnUaus9GwpyKHdDeWaX8RsnfqgYNkbII3VIvgO0NLC9
M2EuogQXXp+Z0N5rCjRlI8+J3ZT4HwJBAJ8tgsmfUcZ2ssM/J2tpxek0jO4NV/5H
+ttNxokaUf6LO/RttwcMpPPKR9gFpOwcjZ3247gU/+NXXFT9JvNEzTkCQBMqpAxk
pw3tV6rF+TZy8Gb+z981KXMG59Xo3WSf2XVmdAIf9/aRIAkFRx3K/DY2X3V3I2dF
NdNCyZuNoy+avOw=
-----END PRIVATE KEY-----";

$publicKey = "
-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCmzzjTtGhdUGPggb76WXV1HePO
KpHg8gEDEH+mSsOUc9q/PTwn7w3u5BL3faC4dGU+ABR24o5wi05tYRkOyYhWTKIx
Nwc12GpujkOkgiuJHFWZsn2SUPiJqgXwWOUyIDpTTB+BmySI9QSc0UYOUuY54DkD
EPviXrniB/BmSQhEawIDAQAB
-----END PUBLIC KEY-----";